### PR TITLE
Upstreamed bot to work on academy.oracle.com as of April 2024

### PR DESCRIPTION
**Pull request by Philotheephilix**
Changes made:

1. Removed login function due to the inclusion of recaptcha
2. added skip on quiz and exam as it is considered incomplete if failed
3. added incomplete detection using flat file (visited.txt)
4. Works well on all platforms (Tested on Windows 11, Kali 2024.1,Mac OS Sonoma)
5. Added single page restart debugging session support

Future ideas:

1. Gpt integration for quiz completion

### CODE REVIEW

**Comment by GrayHat12** [comment]
Hello @Philotheephilix 
Thanks for the Pull Request. Future idea of a GPT integration for quiz completion would be great.
As of now for the existing changes proposed, I currently don't have any credentials to test it myself. I'll try to either get my hands on some working creentials myself to verify the changes. If not possible, i'll just go through the changes manually and merge it if it looks alright.

**Comment by Philotheephilix** [comment]
@GrayHat12 There are still optimizing work to be done like

1. Timeout Optimization (Takes around 20 sec to navigate to next course)
2. More timeout optimization(On poor internet connections wait until the elements appears breaks due to timeout)

will work on these for sure as I have a couple of courses to be completed in this platform.
Anyways thanks for replying and agreeing to work on a 3 year old repository.

**Comment by GrayHat12** [comment]
Hey @Philotheephilix , I could't get hold of any credentials. I am not sure I'll be able to maintain the project after the PR either. Is it fine if I update the README here to redirect users to your fork ?

**Comment by Philotheephilix** [comment]
Ok  @GrayHat12 Then you can update the readme.md for users to get the latest repository changes as well as you cam merge the PR so that the main repository remains updated and doesn't become useless and I will also get the contributions.
I sure will create PR on future changes if you insist.

**Comment by GrayHat12** [comment]
@Philotheephilix  I'll update the README on my repo to just let people know that it is not maintained anymore and I'll add your repo for reference as the maintained version. I think it's better if you own the repo since you're going to be managing it. I would not really be any help if we maintain it on my repo since I have no way to access oracle academy.

**Comment by Philotheephilix** [comment]
Okay then @GrayHat12 Thanks for your time and effort trying to get credentials and everthing.

**Comment by GrayHat12** [comment]
Updated the Project Readme in [Commit](https://github.com/GrayHat12/oracle-bot/commit/ac239518efc50f1ac6971c8ab879fce8caf4b249).
Thanks for maintaining the Project @Philotheephilix. I'll be closing this PR now.

**Pull request closed without merging**
